### PR TITLE
Task/11546

### PR DESCRIPTION
**Pull request by TrinhQuangvo**
### Description
Please explain the changes you made here.

### Checklist
- [ ] Write checklist

---
### https://edu-redmine.sun-asterisk.vn/issues/11518

### CODE REVIEW

**Comment by TrinhQuangvo** [comment]
ready

**Comment by phamvanbk11** [comment]
commented
gộp commit lại em

**Comment by TrinhQuangvo** [comment]
ready

**Comment by TrinhQuangvo** [comment]
ready

**Pull request merged**
